"""feat: added the audit mixin and category model

Revision ID: 420eef3fee02
Revises: 2d1530378c15
Create Date: 2026-03-17 17:36:44.392426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420eef3fee02'
down_revision: Union[str, Sequence[str], None] = '2d1530378c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('roles', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('roles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'roles', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('user_roles', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('user_roles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('user_roles', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_roles', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'deleted_by')
    op.drop_column('user_roles', 'updated_by')
    op.drop_column('user_roles', 'created_by')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'deleted_by')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
