"""updated the id of user

Revision ID: fb85e4e03306
Revises: 1c825038fb67
Create Date: 2026-03-13 19:18:48.011516

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fb85e4e03306'
down_revision: Union[str, Sequence[str], None] = '1c825038fb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
